### PR TITLE
📜 Updated Development Plan to Add Sections 1-4

### PR DESCRIPTION
**Pull request by Isaac020717**
I have added sections 1-4 and regenerated the pdf for our development plan. Please review.

### CODE REVIEW

**Comment by nigelmoses32** [comment]
I'm good with the content of the sections, but I think the formatting at the end of section 4 is causing the following sections to all be indented. If we can change that, I think this pull request is good to go

**Comment by Isaac020717** [comment]
> I'm good with the content of the sections, but I think the formatting at the end of section 4 is causing the following sections to all be indented. If we can change that, I think this pull request is good to go

Good catch! I have fixed the indentation.

**Review by nigelmoses32 — APPROVED** [review]
Looks good, formatting error is fixed. I think it's ready to go

**Review by STARS952 — APPROVED** [review]
Looks ready to me, Issac. Great job.

**Pull request merged**
